const pause_2 = Cypress.env('pause_2')
const pause = Cypress.env('pause')
const pause_1 = Cypress.env('pause_1')
describe('Let Me Be Clear Functionality', function() {
    it('Share Your Story Form', function() {
      cy.visit('https://www.let-me-be-clear.com') 
      Cypress.on('uncaught:exception', (err, runnable) => {
        return false
      })
      cy.viewport(1280, 800)
      cy.wait(pause_2)
      cy.get('#cookie-confirm').click()
      cy.wait(pause)
      cy.get('.hide-lg > [href="/us/en-us/talk-to-your-doctor.html"]').click()
      cy.wait(pause_2)
      cy.get(':nth-child(2) > .column > :nth-child(3) > .link').click()
      cy.wait(pause_2)
      cy.scrollTo('center')
      cy.wait(pause)
      cy.get('.cmp-tabs__tablist > :nth-child(2)').click()
      cy.wait(pause)
      cy.get('.cmp-tabs__tablist > :nth-child(3)').click()
      cy.wait(pause)
      cy.get('.cmp-tabs__tablist > :nth-child(4)').click()
      cy.wait(pause)
      cy.get('.cmp-tabs__tablist > :nth-child(1)').click()
      cy.wait(pause)
      cy.get(':nth-child(2) > :nth-child(2) > :nth-child(1) > .dg__radio').check()
      cy.wait(pause)
      cy.get(':nth-child(3) > :nth-child(2) > :nth-child(2) > .dg__radio').check()
      cy.wait(pause)
      cy.get(':nth-child(4) > :nth-child(2) > :nth-child(3) > .dg__radio').check()
      cy.wait(pause)
      cy.get(':nth-child(5) > :nth-child(2) > :nth-child(4) > .dg__radio').check()
      cy.wait(pause)
      cy.get(':nth-child(6) > :nth-child(2) > :nth-child(5) > .dg__radio').check()
      cy.wait(pause)
      cy.get('.dg__link--next').click()
      cy.wait(pause_2)
      cy.scrollTo('center')
      cy.wait(pause)
      cy.get('#dg-tabpanel_2 > .responsivegrid > .aem-Grid > :nth-child(2) > :nth-child(1)').click()
      cy.wait(pause)
      cy.get('#dg-tabpanel_2 > .responsivegrid > .aem-Grid > :nth-child(3) > :nth-child(1)').click()
      cy.wait(pause)
      cy.get(':nth-child(3) > :nth-child(4)').click()
      cy.wait(pause)
      cy.get('.dg__link--next').click()
      cy.wait(pause_2)
      cy.scrollTo('center')
      cy.wait(pause)
      cy.get('[data-ph-goals="0"] > .dg__disable').click()
      cy.wait(pause)
      cy.get('[data-ph-goals="5"] > .dg__disable').click()
      cy.wait(pause)
      cy.get('[data-ps-goals="2"] > .dg__disable').click()
      cy.wait(pause)
      cy.get('[data-ps-goals="3"] > .dg__disable').click()
      cy.wait(pause)
      cy.get('.dg__link--next').click()
      cy.wait(pause_2)
      cy.get('#dg-tabpanel_4 > .responsivegrid > .aem-Grid > .discussion-checkbox > :nth-child(3)').click()
      cy.wait(pause)
      cy.get('#download-dg').click()





    })
})